import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import 'typeface-open-sans'
import './globals.css'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] })

export const metadata: Metadata = {
  title: 'Huddle landing page with single introductory section',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
